language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
 
  - pear channel-discover pear.phpqatools.org
  - pear install -f phpqatools/phpqatools
  - phpenv rehash
  
  - mysql -e 'create database fabrikar_ci;'
  - mysql fabrikar_ci < fabrik_build/tests/suites/database/stubs/mysql.sql
  
  - "npm install -g jshint"

script:
  - ant travis-phpcs
  - phpunit --configuration travisci-fabrik-phpunit.xml
  
after_script:
  cat fabrik_build/logs/checkstyle.xml
  - "jshint --config=.jshintconfig ."

branches:
  only:
    - joomla3