language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
  - pyrus install --force pear/PHP_CodeSniffer-1.5.0RC3
  - phpenv rehash
  
  - mysql -e 'create database fabrikar_ci;'
  - mysql fabrikar_ci < fabrik_build/tests/suites/database/stubs/mysql.sql

script:
  ant travis-phpcs

branches:
  only:
    - joomla3