language: php

php:
  - 5.3
  - 5.4

before_script:
  - pyrus channel-discover pear.phpunit.de
  - pyrus install --force phpunit/DbUnit
  - pyrus install --force pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --report=full --extensions=php -p -w --standard=build/phpcs/Joomla/ruleset.xml .

branches:
  only:
    - joomla3