# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image:
  name: teamfabrikar/publicfabrik
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL
  
pipelines:
  custom:
    deploy:
    - step:
        name: 'Deploy Public Clone'
        script:
          - cd /work
          - grunt --verbose --gruntfile=/opt/atlassian/pipelines/agent/build/public_clone/Gruntfile.js
